#define HAVE_INTTYPES_H 1
#define HAVE_STDINT_H 1
#define HAVE_STDLIB_H 1
#define HAVE_STRING_H 1
#define HAVE_UNISTD_H 1
#define HAVE_UINTPTR_T 1
#define STDC_HEADERS 1
#define PACKAGE_VERSION "2.0"
